// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf9kfwpoXH5yqnr643vm4gQxXK3Sexb_Q',
    appId: '1:540678482428:web:824c1ff93834dba0f56a79',
    messagingSenderId: '540678482428',
    projectId: 'to-do-taskingcheck',
    authDomain: 'to-do-taskingcheck.firebaseapp.com',
    storageBucket: 'to-do-taskingcheck.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XAhIDKkd_P0BpIeZ5FIjKDQMLia-Eew',
    appId: '1:540678482428:android:3ac1c832fd1623e8f56a79',
    messagingSenderId: '540678482428',
    projectId: 'to-do-taskingcheck',
    storageBucket: 'to-do-taskingcheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXXCMFIwyLPB1xXYkdez-yKVoBgWdnDM',
    appId: '1:540678482428:ios:01aeea7477158722f56a79',
    messagingSenderId: '540678482428',
    projectId: 'to-do-taskingcheck',
    storageBucket: 'to-do-taskingcheck.firebasestorage.app',
    androidClientId: '540678482428-k2qnupvouda49pqiurbifpbstdk7f2ek.apps.googleusercontent.com',
    iosClientId: '540678482428-9gb0r3tjq5pfrv1uh737cqtcl4cpudcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskingcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXXCMFIwyLPB1xXYkdez-yKVoBgWdnDM',
    appId: '1:540678482428:ios:01aeea7477158722f56a79',
    messagingSenderId: '540678482428',
    projectId: 'to-do-taskingcheck',
    storageBucket: 'to-do-taskingcheck.firebasestorage.app',
    androidClientId: '540678482428-k2qnupvouda49pqiurbifpbstdk7f2ek.apps.googleusercontent.com',
    iosClientId: '540678482428-9gb0r3tjq5pfrv1uh737cqtcl4cpudcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskingcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf9kfwpoXH5yqnr643vm4gQxXK3Sexb_Q',
    appId: '1:540678482428:web:7030734888feb37ff56a79',
    messagingSenderId: '540678482428',
    projectId: 'to-do-taskingcheck',
    authDomain: 'to-do-taskingcheck.firebaseapp.com',
    storageBucket: 'to-do-taskingcheck.firebasestorage.app',
  );
}
